# Generated by Django 5.1.7 on 2025-03-31 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fun_lists", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fun_lists.genre",
                    ),
                ),
                (
                    "ott",
                    models.ManyToManyField(blank=True, null=True, to="fun_lists.ott"),
                ),
            ],
        ),
    ]
