# Generated by Django 5.1.7 on 2025-03-31 13:57

import django.db.models.deletion
import fun_lists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("fun_lists", "0006_alter_list_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={
                    "model__in": [fun_lists.models.Movie, fun_lists.models.Series]
                },
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
