# Generated by Django 5.1.7 on 2025-03-31 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("fun_lists", "0007_alter_list_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={"model__in": ["Movie", "Series"]},
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
